# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrname', models.CharField(max_length=20)),
                ('addrdetail', models.CharField(max_length=200)),
                ('addrcode', models.IntegerField()),
                ('addrtel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodID', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Dict')),
            ],
        ),
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('gdescrption', models.CharField(max_length=200)),
                ('gunit', models.CharField(max_length=20)),
                ('gprice', models.CharField(max_length=20)),
                ('gdetails', models.CharField(max_length=1000)),
                ('dictID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dict')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
                ('lpassword', models.CharField(max_length=20)),
                ('lemail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('detail', models.TextField(max_length=1000)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.DecimalField(decimal_places=0, max_digits=4)),
                ('orderSum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('utel', models.IntegerField()),
                ('uaddress', models.CharField(max_length=200)),
                ('ucreatetime', models.DateTimeField()),
                ('loginID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Login')),
            ],
        ),
        migrations.CreateModel(
            name='ViewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddr', models.CharField(max_length=20)),
                ('goodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GoodInfo')),
            ],
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='goodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GoodInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserInfo'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserInfo'),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='loginID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.UserInfo'),
        ),
    ]
